name: RealmsStory
version: 1.0pre
description: Dynamic quests and characters, that are tailored to your world.
author: Kyle_Necrowolf
website: http://WolfiaMC.com/plugins

main: com.kylenecrowolf.realmsstory.Main
depend: [RealmsCore, Citizens]

commands:
  realmsstory:
    description: Display Realms plugin version

  tag:
    description: Manage tags for objects
    usage: "Usage: /tag <info/entity/player/npc> <target> [add/remove] [tag]"