name: ProjectStory
version: 1.0pre
description: Dynamic quests and characters, that are tailored to your world.
author: Kyle Nanakdewa
website: http://plugins.akenland.com

main: com.kylenanakdewa.story.StoryPlugin
depend: [CoRE, Citizens]

commands:
  story:
    description: Display Project Story plugin version

  tag:
    description: Manage tags for objects
    usage: "Usage: /tag <info/entity/player/npc> <target> [add/remove] [tag]"
  
  journal:
    description: Manage journals for characters
    usage: "Usage: /journal [list/add/remove/reset] [objectiveID] [-player playerName] [-active/-discovered/-completed]"